#!/bin/bash
# wali : Wal Improved

# pass all arguments to wal
wal "$@"

# source wal colors
. "${HOME}/.cache/wal/colors.sh"

# change color in css file
sed -i '/--bg-color:/c\--bg-color: '$color1';' ${HOME}/.mozilla/firefox/ifajf7uc.default-release/chrome/userChrome.css


